#Requires -Version 5.1
<#
.SYNOPSIS
  IntelliStock — quick install + start (Windows / PowerShell).

.DESCRIPTION
  1. Verifies prerequisites (docker, docker compose).
  2. Creates .env with safe defaults + a freshly-generated Fernet
     INTELLISTOCK_CRED_KEY (only if .env doesn't already exist).
  3. Builds the backend image.
  4. Brings up the full stack (rethinkdb, neo4j, backend, api,
     frontend, price-service, backtest-engine, credential-service).
  5. Waits for the API health check, then prints local URLs.

.NOTES
  Run from any shell:    powershell -ExecutionPolicy Bypass -File .\install.ps1
  Or from PowerShell:    .\install.ps1
#>

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $RepoRoot

# ── Pretty-print helpers ──────────────────────────────────────────
function Info($msg) { Write-Host "==> "  -ForegroundColor Cyan   -NoNewline; Write-Host $msg }
function Ok  ($msg) { Write-Host " ✓  "  -ForegroundColor Green  -NoNewline; Write-Host $msg }
function Warn($msg) { Write-Host " !  "  -ForegroundColor Yellow -NoNewline; Write-Host $msg }
function Fail($msg) { Write-Host " ✗  "  -ForegroundColor Red    -NoNewline; Write-Host $msg; exit 1 }

function Banner {
    $art = @"
██╗███╗   ██╗████████╗███████╗██╗     ██╗     ██╗
██║████╗  ██║╚══██╔══╝██╔════╝██║     ██║     ██║
██║██╔██╗ ██║   ██║   █████╗  ██║     ██║     ██║
██║██║╚██╗██║   ██║   ██╔══╝  ██║     ██║     ██║
██║██║ ╚████║   ██║   ███████╗███████╗███████╗██║
╚═╝╚═╝  ╚═══╝   ╚═╝   ╚══════╝╚══════╝╚══════╝╚═╝
   ███████╗████████╗ ██████╗  ██████╗██╗  ██╗
   ██╔════╝╚══██╔══╝██╔═══██╗██╔════╝██║ ██╔╝
   ███████╗   ██║   ██║   ██║██║     █████╔╝
   ╚════██║   ██║   ██║   ██║██║     ██╔═██╗
   ███████║   ██║   ╚██████╔╝╚██████╗██║  ██╗
   ╚══════╝   ╚═╝    ╚═════╝  ╚═════╝╚═╝  ╚═╝
"@
    # Console host: tag PowerShell-friendly violet via the named Magenta colour.
    # ANSI-aware terminals (Windows Terminal, VS Code) render this as bright purple.
    Write-Host $art -ForegroundColor Magenta
    Write-Host ''
}

Banner

# ── Prerequisite checks ───────────────────────────────────────────
function Test-Cmd($name) { $null -ne (Get-Command $name -ErrorAction SilentlyContinue) }

Info 'Checking prerequisites…'
if (-not (Test-Cmd 'docker')) {
  Fail "docker not found in PATH. Install Docker Desktop: https://docs.docker.com/desktop/install/windows-install/"
}
& docker compose version > $null 2>&1
if ($LASTEXITCODE -ne 0) {
  Fail "'docker compose' subcommand not available. Update Docker Desktop."
}
& docker info > $null 2>&1
if ($LASTEXITCODE -ne 0) {
  Fail 'Docker daemon is not running. Start Docker Desktop and re-run this script.'
}
Ok 'docker + docker compose present and daemon is up'

# ── .env scaffold ─────────────────────────────────────────────────
$EnvFile = Join-Path $RepoRoot '.env'
if (Test-Path $EnvFile) {
  Ok '.env already exists — leaving it alone'
} else {
  Info 'Generating .env with safe defaults'

  # Helper: cryptographically random urlsafe-b64 string of N bytes
  # (no '=' padding, since we may substring the result).
  function New-UrlSafeKey([int]$byteCount) {
    $b = New-Object byte[] $byteCount
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    return ([Convert]::ToBase64String($b)).Replace('+','-').Replace('/','_').TrimEnd('=')
  }

  # Fernet key = 32 random bytes. MUST be stable for the lifetime of the
  # install — losing it makes encrypted brokerage credentials unreadable.
  $credKey = New-UrlSafeKey 32
  # Signup gate token: required by /auth/signup. Keep private.
  $secretAuthKey = New-UrlSafeKey 32
  # Default admin password: 16 random URL-safe characters. 16 input bytes
  # -> ~22 b64 chars before the substring, so length is always sufficient.
  $adminPassword = (New-UrlSafeKey 16).Substring(0, 16)
  # JWT signing key: 32 random bytes.
  $jwtSecret = New-UrlSafeKey 32
  # Neo4j password — only honoured at first-boot. 20 input bytes -> ~27
  # b64 chars, cut to 20 to guarantee the substring length.
  $neo4jPassword = (New-UrlSafeKey 20).Substring(0, 20)

  $envContent = @"
# ── Auto-generated by install.ps1 — keep INTELLISTOCK_CRED_KEY stable ──
# Losing this key makes encrypted brokerage credentials unrecoverable.

# Fernet key for credential encryption (32 random bytes, urlsafe-b64)
INTELLISTOCK_CRED_KEY=$credKey

# Signup gate token. /auth/signup rejects any request that doesn't carry
# this exact value. Keep it private -- anyone with it can register users.
SECRET_AUTH_KEY=$secretAuthKey

# Default admin account auto-provisioned on first backend boot. Change
# DEFAULT_ADMIN_PASSWORD here if you want a memorable one -- the value
# below is the auto-generated random password printed at install time.
DEFAULT_ADMIN_USERNAME=admin
DEFAULT_ADMIN_PASSWORD=$adminPassword

# JWT signing key. Backend refuses to mint tokens if this is unset
# or weak; rotating it logs out every active session.
JWT_SECRET=$jwtSecret

# CORS origins (comma-separated). Empty = no cross-origin allowed at all,
# which is correct for the default single-host deploy. Set this only
# when serving the frontend from a different host than the API.
CORS_ALLOW_ORIGINS=

# Set API_DOCS_PUBLIC=true to expose /docs and /openapi.json. They're
# off by default because the schema is an attack-surface map.
API_DOCS_PUBLIC=

# Service ports
API_PORT=8011
FRONTEND_PORT=3000
RETHINKDB_WEB_PORT=8080
DISCORD_BOT_HTTP_PORT=8050

# How the JS bundle reaches the API in the browser. For local dev
# the frontend container's nginx routes /api -> http://intellistock-api,
# so leaving this blank is fine.
VITE_API_URL=
API_URL=http://intellistock-api:8011

# Preview mode: set to "true" to build a landing-only frontend (no
# portal, GitHub CTA in place of auth). Useful for hosting the
# marketing page on its own domain. Empty = full portal.
VITE_PREVIEW_MODE=

# RethinkDB host. Inside docker-compose this is the service name
# 'rethinkdb' (set in compose). Out-of-container CLI scripts default
# to localhost; override here if RethinkDB lives on another host.
RETHINKDB_HOST=localhost
RETHINKDB_PORT=28015

# Neo4j (used by Graph Nexus). Change NEO4J_PASSWORD BEFORE the first
# 'up' if you want a different password — Neo4j only honors NEO4J_AUTH
# on first-boot, otherwise you must reset via cypher-shell. NEO4J_URI
# is consumed by the engine + CLI; defaults to localhost.
NEO4J_URI=bolt://localhost:7687
NEO4J_USER=neo4j
NEO4J_PASSWORD=$neo4jPassword

# Optional: Discord bot. Leave DISCORD_BOT_TOKEN blank to skip.
DISCORD_BOT_TOKEN=
DISCORD_BOT_API_KEY=

# LLM provider credentials are NOT configured here. Add them through
# the Models tab in the web UI after onboarding -- the Models table
# is the single source of truth for OpenAI / Azure / Gemini /
# DeepSeek / NVIDIA keys for the chatbot and strategies that use LLMs.

# Data-source keys for the Graph Nexus engine. Both are optional --
# the engine degrades to free fallbacks where it can.
BENZINGA_API_KEY=
POLYGON_API_KEY=

# Optional Neo4j heap tuning. Default is 4 GB; lower for the
# minimum hardware tier (see README -> Hardware).
# NEO4J_HEAP_MAX_SIZE=4G
"@

  # UTF-8 without BOM — docker-compose's env_file parser is picky about BOMs.
  [System.IO.File]::WriteAllText($EnvFile, $envContent, (New-Object System.Text.UTF8Encoding $false))
  Ok "Wrote $EnvFile  (review and add any optional API keys you have)"
}

# ── Helper: read a value from .env without sourcing it ────────────
function Get-EnvValue($key, $default) {
  $line = Get-Content $EnvFile | Where-Object { $_ -match "^\s*$key\s*=" } | Select-Object -First 1
  if (-not $line) { return $default }
  $val = ($line -split '=', 2)[1].Trim().Trim('"')
  if ([string]::IsNullOrWhiteSpace($val)) { return $default }
  return $val
}

# ── Build & launch ────────────────────────────────────────────────
Info 'Building backend image (this takes a few minutes the first time)…'
& docker compose build backend
if ($LASTEXITCODE -ne 0) { Fail 'docker compose build failed.' }
Ok 'Backend image built'

Info 'Starting the full stack in the background…'
& docker compose up -d
if ($LASTEXITCODE -ne 0) { Fail 'docker compose up failed.' }
Ok 'Containers up'

# ── Health wait ───────────────────────────────────────────────────
Info 'Waiting for the API to come online…'
$apiPort = Get-EnvValue 'API_PORT' '8011'
$healthUrl = "http://localhost:$apiPort/health"

$attempts = 60
$healthy = $false
for ($i = 1; $i -le $attempts; $i++) {
  try {
    $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
    if ($resp.StatusCode -eq 200) {
      Ok "API healthy at $healthUrl"
      $healthy = $true
      break
    }
  } catch {
    # Still booting. Sleep + retry.
  }
  Start-Sleep -Seconds 2
}
if (-not $healthy) {
  Warn "API didn't respond at $healthUrl after $attempts attempts."
  Warn 'Tail logs with:  docker compose logs -f api'
}

# ── Done ──────────────────────────────────────────────────────────
$frontendPort = Get-EnvValue 'FRONTEND_PORT'    '3000'
$rdbWebPort   = Get-EnvValue 'RETHINKDB_WEB_PORT' '8080'
$adminUser    = Get-EnvValue 'DEFAULT_ADMIN_USERNAME' 'admin'
$adminPass    = Get-EnvValue 'DEFAULT_ADMIN_PASSWORD' ''

Write-Host ''
Write-Host 'IntelliStock is up.' -ForegroundColor Green
Write-Host ''
Write-Host "  Frontend            http://localhost:$frontendPort"
Write-Host "  API                 http://localhost:$apiPort"
Write-Host "  RethinkDB admin     http://localhost:$rdbWebPort"
Write-Host '  Neo4j browser       http://localhost:7474   (user: neo4j / pass: see NEO4J_PASSWORD in .env)'
Write-Host ''
Write-Host '  Default admin login' -ForegroundColor Magenta
Write-Host "    Username          $adminUser"
Write-Host "    Password          $adminPass"
Write-Host '    (also stored in .env as DEFAULT_ADMIN_PASSWORD - change there + restart to rotate)' -ForegroundColor Yellow
Write-Host ''
Write-Host '  Logs                docker compose logs -f'
Write-Host '  Stop                docker compose down'
Write-Host '  Stop + wipe data    docker compose down -v   ' -NoNewline
Write-Host '(deletes RethinkDB + Neo4j volumes)' -ForegroundColor Yellow
Write-Host ''
Write-Host "Open the frontend, walk through onboarding, and you're trading."
