/// SF Symbols for the Material icon names the Flutter app used — every key in
/// `material_symbols.dart` plus every raw `Icons.*` name in `mobile/lib`.
/// Ported views keep the Dart name at the call site (`Symbol.named("hub")`), so
/// a reader can trace each glyph back to the original. `_outlined`,
/// `_rounded` and `_outline` suffixes resolve to the base name.
nonisolated enum Symbol {
    static let fallback = "circle"

    static func named(_ material: String) -> String {
        if let sf = map[material] { return sf }
        for suffix in ["_outlined", "_rounded", "_outline"] where material.hasSuffix(suffix) {
            if let sf = map[String(material.dropLast(suffix.count))] { return sf }
        }
        return fallback
    }

    static var materialNames: [String] { map.keys.sorted() }

    private static let map: [String: String] = [
        // material_symbols.dart
        "dashboard": "square.grid.2x2",
        "account_balance": "building.columns",
        "memory": "cpu",
        "analytics": "chart.bar.xaxis",
        "sports_soccer": "soccerball",
        "smart_toy": "sparkles",
        "hub": "point.3.connected.trianglepath.dotted",
        "schema": "flowchart",
        "psychology": "brain.head.profile",
        "payments": "creditcard",
        "person": "person",
        "logout": "rectangle.portrait.and.arrow.right",
        "menu": "line.3.horizontal",
        "close": "xmark",
        "refresh": "arrow.clockwise",
        "add": "plus",
        "add_circle": "plus.circle",
        "open_in_new": "arrow.up.right.square",
        "open_in_full": "arrow.up.left.and.arrow.down.right",
        "close_fullscreen": "arrow.down.right.and.arrow.up.left",
        "play_circle": "play.circle",
        "play_arrow": "play.fill",
        "play_disabled": "nosign",
        "pause": "pause.fill",
        "pause_circle": "pause.circle",
        "stop": "stop.fill",
        "stop_circle": "stop.circle",
        "link": "link",
        "tune": "slider.horizontal.3",
        "delete": "trash",
        "delete_sweep": "xmark.bin",
        "warning": "exclamationmark.triangle",
        "error": "exclamationmark.circle",
        "settings": "gearshape",
        "notifications": "bell",
        "discord": "bubble.left.and.bubble.right",
        "push_pin": "pin.fill",
        "push_pin_outlined": "pin",
        "expand_more": "chevron.down",
        "expand_less": "chevron.up",
        "history": "clock.arrow.circlepath",
        "chat": "bubble.left",
        "send": "arrow.up.circle.fill",
        "lock": "lock",
        "visibility": "eye",
        "visibility_off": "eye.slash",
        "arrow_forward": "arrow.right",
        "arrow_back": "arrow.left",
        "arrow_downward": "arrow.down",
        "arrow_upward": "arrow.up",
        "unfold_more": "chevron.up.chevron.down",
        "monitoring": "waveform.path.ecg",
        "trending_up": "chart.line.uptrend.xyaxis",
        "trending_down": "chart.line.downtrend.xyaxis",
        "show_chart": "chart.xyaxis.line",
        "candlestick_chart": "chart.bar",
        "area_chart": "chart.line.flattrend.xyaxis",
        "bar_chart": "chart.bar",
        "bar_chart_4_bars": "chart.bar.fill",
        "search": "magnifyingglass",
        "savings": "banknote",
        "replay": "arrow.counterclockwise",
        "emoji_events": "trophy",
        "score": "list.number",
        "gavel": "checkmark.seal",
        "check_circle": "checkmark.circle.fill",
        "cancel": "xmark.circle.fill",
        "power_off": "power",
        "hourglass_empty": "hourglass",
        "auto_awesome": "sparkles",
        "newspaper": "newspaper",
        "terminal": "terminal",
        "filter_alt_off": "line.3.horizontal.decrease.circle",
        "add_shopping_cart": "cart.badge.plus",
        "database": "cylinder.split.1x2",
        "schedule": "clock",
        "reset_wrench": "wrench.and.screwdriver",
        "more_horiz": "ellipsis",
        "progress_activity": "rays",
        "monetization_on": "dollarsign.circle",
        "block": "nosign",
        "rocket_launch": "arrow.up.forward.circle",
        "bolt": "bolt.fill",
        "check": "checkmark",
        "currency_bitcoin": "bitcoinsign.circle",
        "edit": "pencil",
        "lightbulb": "lightbulb",
        // Raw Icons.* names used directly in mobile/lib
        "chevron_right": "chevron.right",
        "chevron_left": "chevron.left",
        "check_circle_outline": "checkmark.circle",
        "science": "flask",
        "play_circle_outline": "play.circle",
        "info": "info.circle",
        "info_outline": "info.circle",
        "error_outline": "exclamationmark.circle",
        "copy": "doc.on.doc",
        "content_copy": "doc.on.doc",
        "warning_amber": "exclamationmark.triangle",
        "receipt_long": "list.bullet.rectangle.portrait",
        "person_outline": "person",
        "pause_circle_outline": "pause.circle",
        "keyboard_arrow_up": "chevron.up",
        "keyboard_arrow_down": "chevron.down",
        "fingerprint": "touchid",
        "circle": "circle",
        "chat_bubble_outline": "bubble.left",
        "sync": "arrow.triangle.2.circlepath",
        "storage": "externaldrive",
        "scoreboard": "sportscourt",
        "pending": "ellipsis.circle",
        "not_interested": "nosign",
        "north_east": "arrow.up.right",
        "network_check": "network",
        "monitor_heart": "waveform.path.ecg.rectangle",
        "lock_outline": "lock",
        "forum": "bubble.left.and.bubble.right",
        "exit_to_app": "rectangle.portrait.and.arrow.right",
        "calendar_today": "calendar",
        "cable": "cable.connector",
        "build": "wrench.adjustable",
        "autorenew": "arrow.triangle.2.circlepath",
        "arrow_back_ios_new": "chevron.left",
        "add_circle_outline": "plus.circle",
    ]
}
